# Generated by Django 5.1.1 on 2024-11-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donate_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollars', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('user', models.CharField(default='', max_length=30)),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='points_model',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('points', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
